#!/usr/bin/env python3

crono = {
    '0': ('Plano de ensino', 1),
    '1': ('Conjuntos, funções', 1),
    '2': ('Relações de equivalência, conjuntos quocientes', 1),
    '3': ('Operações binárias, grupos', 1),
    '4': ('Grupos simétricos, notação cíclica', 1),
    '5': ('Grupos alternados, grupos dihedrais', 1),
    '6': ('Subgrupos, geradores', 1),
    '7': ('Classes laterais, Teorema de Lagrange', 1),
    '8': ('Classes de conjugação, Equação de Classes, p-grupos finitos', 1),
    '9': ('Subgrupos normais, grupos quocientes', 1),
    '10': ('Homomorfismos de gupos, Teoremas do Isomorfismos', 1),
    '11': ('Teorema de Cayley, Teorema da Correspondência', 1),
    '12': ('Resolução de exercícios', 1),
    '13': ('Primeira prova escrita', 1),
    '14': ('Ações de grupos, órbita e estabilizadores', 1),
    '15': ('Teorema de Cauchy, Teoremas de Sylow (enunciado)', 1),
    '16': ('Teoremas de Sylow (demonstração)', 1),
    '17': ('Resolução de exercícios', 1),
    '18': ('Teorema Fundamental dos Grupos Abelianos Finitos', 1),
    '19': ('Anéis e subanéis', 1),
    '20': ('Ideais e anéis quocientes', 1),
    '21': ('Homomorfismos de anéis, Teoremas do Isomorfismo', 1),
    '22': ('Teorema da Correspondência', 1),
    '23': ('Domínios de ideais principais', 1),
    '24': ('Domínios de integridade', 1),
    '25': ('Domínios euclidianos', 1),
    '26': ('Corpos', 1),
    '27': ('Corpos finitos', 1),
    '28': ('Extensões de corpos, Teorema de Kronecker', 1),
    '29': ('Corpo das frações de um domínio de integridade', 1),
    '30': ('Aula de resolução de exercícios', 1),
    '31': ('Segunda prova escrita', 1),
    '32': ('Seminários: 1 e 2', 1),
    '33': ('Seminários: 3 e 4', 1),
    '34': ('Seminários: 5 e 6', 1),
    '35': ('Seminários: 7 e 8', 1),
    '36': ('Seminários: 9 e 10', 1),
    '37': ('Recuperação', 1),
}
