#!/usr/bin/env python3

crono = {
    '0': ('Plano de ensino', 1),
    '1': ('Espaços vetorias: definição, propriedades', 1),
    '2': ('Espaços vetoriais: exemplos', 1),
    '3': ('Subespaços vetoriais', 1),
    '4': ('Geradores', 1),
    '5': ('Dependência e independência linear', 1),
    '6': ('Bases e dimensão', 1),
    '7': ('Transformções lineares', 1),
    '8': ('Matriz de uma transformação linear', 1),
    '9': ('Produto de Transformações lineares', 1),
    '10': ('Núcleo e Imagem', 1),
    '11': ('Aula de resolução de exercícios', 1),
    '12': ('Primeira prova escrita', 1),
    '13': ('Soma direta e projeções', 1),
    '14': ('Eliminação', 1),
    '15': ('Produto interno: definição, ortogonalidade', 1),
    '16': ('Cauchy-Schwarz, normas', 1),
    '17': ('Algoritmo de Gram-Schmidt', 1),
    '18': ('Operador adjunto', 1),
    '19': ('Operadores autoadjuntos: Teorema espectral', 1),
    '20': ('Operadores ortogonais', 1),
    '21': ('Operadores Normais (caso real)', 1),
    '22': ('Pseudo-inversa', 1),
    '23': ('Aula de resolução de exercícios', 1),
    '24': ('Segunda prova escrita', 1),
    '25': ('Tópicos matriciais: decomposição LU com pivotação parcial', 1),
    '26': ('Resolução de sistemas lineares', 1),
    '27': ('Formas quadráticas', 1),
    '28': ('Determinantes', 1),
    '29': ('Autovalores e autovetores, polinômio característico', 1),
    '30': ('Forma canônica racional: parte 1', 1),
    '31': ('Forma canônica racional: parte 2', 1),
    '32': ('Aplicação: EDOs lineares de primeira e segunda ordem', 1),
    '33': ('Aula de resolução de exercícios', 1),
    '34': ('Terceira prova escrita', 1),
    '35': ('Aula de resolução de exercícios', 1),
    '36': ('Aula de resolução de exercícios', 1),
    '37': ('Recuperação', 1),
}
