#!/usr/bin/env python3

crono = {
    '0': ('Plano de Ensino', 1),
    '1': ('O plano complexo', 1),
    '2': ('A exponencial', 1),
    '3': ('Noções de topologia do plano', 1),
    '4': ('Sequências de números complexos', 1),
    '5': ('Séries de números complexos', 1),
    '6': ('Funções complexas de variável complexa', 1),
    '7': ('Limites', 1),
    '8': ('Propriedades dos limites', 1),
    '9': ('Continuidade', 1),
    '10': ('Funções analíticas: as Equações de Cauchy-Riemann', 1),
    '11': ('Condição suficiente para que uma função seja analítica', 1),
    '12': ('Cauchy-Riemann em coordenadas polares, logarítmos, etc.', 1),
    '13': ('Teorema da função inversa', 1),
    '14': ('Funções trigonométricas e trigonométricas inversas, etc.', 1),
    '15': ('Aula de resolução de exercícios', 1),
    '16': ('Primeira prova escrita', 1),
    '17': ('Arcos, contornos, Teorema de Jordan, conectividade simples', 1),
    '18': ('Integrais de contorno e suas propriedades', 1),
    '19': ('Teoremas de Green e de Cauchy', 1),
    '20': ('Primitivas', 1),
    '21': ('Fórmula Integral de Cauchy', 1),
    '22': ('Derivadas de todas as ordens, funções harmônicas', 1),
    '23': ('Princípio do Módulo Máximo, Problemas de Dirichlet', 1),
    '24': ('Problemas de Neumann, Séries de funções complexas', 1),
    '25': ('Convergências pontual e uniforme, séries de potências', 1),
    '26': ('Séries de Taylor', 1),
    '27': ('Séries de Laurent', 1),
    '28': ('Singularidades isoladas: removíveis, pólos e essenciais', 1),
    '29': ('Teorema dos Resíduos', 1),
    '30': ('Integrais impróprias de funções racionais', 1),
    '31': ('Integrais envolvendo funções trigonométricas', 1),
    '32': ('Aula de resolução de exercícios', 1),
    '33': ('Segunda prova escrita', 1),
    '34': ('Seminários: 1 e 2', 1),
    '35': ('Seminários: 3 e 4', 1),
    '36': ('Seminário: 5', 1),
    '37': ('Recuperação', 1),
}
